object BuildDependenciesVersions {
    const val GRADLE = "4.1.3"
    const val GOOGLE_SERVICE = "4.3.5"
    const val KOTLIN = "1.5.0"
    const val CORE_KTX = "1.3.2"
    const val RECYCLE_VIEW = "1.2.0"
    const val CONSTRAIN_LAYOUT = "2.0.4"
    const val APPCOMPAT = "1.2.0"
    const val CARD_VIEW = "1.0.0"
    const val VIEW_PAGER = "1.0.0"
    const val MATERIAL = "1.3.0"
    const val NAVIGATION = "2.3.5"
    const val ROOM = "2.3.0"
    const val FIREBASE_ANALYTICS = "18.0.3"
    const val LOTTIE = "3.4.1"
    const val GLIDE = "4.10.0"
    const val CIRCLE_IMAGE_VIEW = "3.1.0"
    const val PICASSO = "2.71828"
    const val SOCKET = "1.0.0"
    const val RETROFIT = "2.9.0"
    const val FREE_DRAW_VIEW = "1.1.2"
    const val TED_PERMISSION = "2.2.3"
    const val WHEEL_PICKER = "1.1.3"
    const val CHROME_TAB = "28.0.0"
    const val HILT = "2.31-alpha"

    //Test
    const val JUNIT = "4.13.2"
    const val EXT = "1.1.2"
    const val ESPRESSO = "3.3.0"
}